services:
  keycloak:
    build: .
    image: keycloak-petshop
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: vmas
      KEYCLOAK_ADMIN_PASSWORD: abc123@
    command: start-dev --import-realm